### ISSUE TITLE
微信新版本需要更新路径

### ISSUE THREAD

**Issue by Scenny** [naturali/issues#18]
TransformMoney
WechatChargePhone
WechatReceiveMoney
面对面红包 	
微信零钱明细	
WechatChangeLanguage
SearchCategoryInApp （B65E719FBD6CD526 ）

**Comment by lindek** [comment]
Fixed:
WechatReceiveMoney
面对面红包

These seem to work as is:
TransformMoney
WechatChargePhone
WechatChangeLanguage

Not sure the functionality still exist:
微信零钱明细

Not sure what's the problem:
SearchCategoryInApp （B65E719FBD6CD526 ）
The query was 微信流量统计, which seems to work as is
