### ISSUE TITLE
火山公园 -> 火山公民 1C2CBA52BF69938B

### ISSUE THREAD

**Issue by xiaoyunwu** [naturali/issues#34]

**Comment by nestle1993** [comment]
48 (huo2, 0.0329), (huo3, 0.9045), (wo3, 0.0509)
56 (shan1, 0.9994)
65 (gong1, 0.9887)
71 (ming2, 0.4201), (min2, 0.5449)
top 10
huo3_火 shan1_山 gong1_公 yuan2_园-5.35506
huo3_火 shan1_山 gong1_公 min2_民-7.60427
huo3_火 shan1_山 gong1_功 ming2_名-8.38742
huo3_火 shan1_山 gong1_公 ming2_明-9.06264
huo3_火 shan1_珊 gong1_公 min2_民-9.24841
huo3_火 shan1_山 gong1_宫 ming2_名-9.46242
huo3_火 shan1_山 gong1_龚 ming2_明-9.74571
huo3_火 shan1_山 gong1_工 ming2_名-9.78378
huo3_火 shan1_珊 gong1_功 ming2_名-9.90442
huo3_火 shan1_山 gong1_宫 ming2_明-10.0464

seems the fst's problem (no aca words)
