### ISSUE TITLE
“给小曹发信息”-刚开始正确识别，执行的时候变成了“给肖超发信息”类似的例子也还有

### ISSUE THREAD

**Issue by rhapsolo** [naturali/issues#77]

**Comment by nestle1993** [comment]
if you have "肖超" in your contact list but not "小曹", it will always be replaced.

**Comment by rhapsolo** [comment]
actually i do have 小曹 but not 肖超 in my contact list

_____________________________

王丽 Li Wang
Marketing Manager, Naturali奇点机智
Tel: +86-152 1059 8732
Email: li.wang@naturali.io

**Comment by Xinlw** [comment]
语音识别“小曹” 后又会强制改为 “小草”
